### ISSUE TITLE
Dialog 设计

### ISSUE THREAD

**Issue by hanai** [hanai/blog#3]
``` jade
.vui-dialog-container
  .vui-dialog-mask
  .vui-dialog
    .vui-dialog-hd
      .vui-dialog-title 通知
    .vui-dialog-bd
    .vui-dialog-ft
      a.default(href="javascript:void(0)") 取消
      a.primary(href="javascript:void(0)") 确定
```

``` scss
.vui-dialog-ft {
  display: flex;
  position: relative;

  &:after {
    content: " ";
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 1px;
    border-top: 1px solid #e5e5e5;
    transform-origin: 0 0;
    transform: scaleY(.5);
  }
}

.vui-dialog-ft a {
  position: relative;
  display: block;

  &:first-child {
    &:after {
      display: none;
    }
  }

  &:after {
    content: ' ';
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 1px;
    border-left: 1px solid #e5e5e5;
    transform-origin: 0 0;
    transform: scaleX(.5);
  }
}
```
