### ISSUE TITLE
transform: matrix() & matrix3d()

### ISSUE THREAD

**Issue by hanai** [hanai/blog#9]
# matrix()
### 笛卡尔坐标系

![image](https://cloud.githubusercontent.com/assets/1222115/16416811/88f62880-3d76-11e6-98c2-17f3420300eb.png)

原点 (0, 0) 在元素的左上角。每一个点由向量 (x, y) 标记。

进行变换的时候，对每个点做矩阵乘法：

![image](https://cloud.githubusercontent.com/assets/1222115/16417086/4eb89cd8-3d77-11e6-874c-4c54a551f989.png)

可以在一行中应用多次变换：

![image](https://cloud.githubusercontent.com/assets/1222115/16417240/73c95a1c-3d77-11e6-9471-af295088e3f9.png)

使用这种标记可以描述多种常用的变换：旋转、缩放、倾斜。事实上所有这些变换都是线性函数可以描述的。使用这种标记时有一种非线性的变换需要当做特例，就是平移。平移向量 (tx, ty) 必须作为两个附加的参数来表述。
#### 语法

> matrix(a, b, c, d, tx, ty)
#### 值
- a, b, c, d 描述线性变换的数字
- 描述平移的数字
#### 示例

``` css
.pane {
  background: green;
  width: 200px;
  height: 200px;
}

.box {
  float: left;
  background: blue;
  width: 50px;
  height: 50px;
  transform-origin: 0 0;
}

.more {
  float: left;
  width: 50px;
  height: 50px;
  background: red;
}
```
- 左右各平移 4px

``` css
.box {
  transform: matrix(1, 0, 0, 1, 4, 4);
}
```

![image](https://cloud.githubusercontent.com/assets/1222115/16418513/b6e91fb2-3d7c-11e6-8502-2ac7b681fef4.png)
- 放大两倍

``` css
.box {
  transform: matrix(2, 0, 0, 2, 0, 0);
}
```

![image](https://cloud.githubusercontent.com/assets/1222115/16418624/4d0cf234-3d7d-11e6-9233-bd6080dcd201.png)
- 旋转

``` css
.box {
  transform: matrix(2, 1, -1, 2, 0, 0);
}
```

![image](https://cloud.githubusercontent.com/assets/1222115/16418804/f6c51e28-3d7d-11e6-9185-4f56c0cc674f.png)
# 附：为什么平移不是线性变换？

一个线性变换 f，会使 f(x + y) = f(x) + f(y) 成立

平移：y = ax + b
